// <auto-generated />
using System;
using EFCorePrototype.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCorePrototype.Migrations
{
    [DbContext(typeof(EFCorePrototypeDatabase))]
    partial class EFCorePrototypeDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("EFCorePrototype.Model.ClassroomEntity", b =>
                {
                    b.Property<string>("Room")
                        .HasColumnType("TEXT");

                    b.Property<int>("Floor")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("TEXT");

                    b.HasKey("Room", "Floor");

                    b.HasIndex("SchoolId");

                    b.ToTable("ClassroomEntities");
                });

            modelBuilder.Entity("EFCorePrototype.Model.PerformanceEntity", b =>
                {
                    b.Property<string>("KeyOne")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyTwo")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyThree")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyFour")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyFive")
                        .HasColumnType("TEXT");

                    b.HasKey("KeyOne", "KeyTwo", "KeyThree", "KeyFour", "KeyFive");

                    b.ToTable("PerformanceEntities");
                });

            modelBuilder.Entity("EFCorePrototype.Model.SchoolEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SchoolEntities");
                });

            modelBuilder.Entity("EFCorePrototype.Model.ClassroomEntity", b =>
                {
                    b.HasOne("EFCorePrototype.Model.SchoolEntity", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });
#pragma warning restore 612, 618
        }
    }
}
